### ISSUE TITLE
ws and rest cannot be served in the same port

### ISSUE THREAD

**Issue by georve** [alexkander/loopback4-example-websocket-app#1]
when i run this code

Cannot start the application. Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at HttpServer.start (/home/georman/Documents/loopback4-example-websocket-app/node_modules/@loopback/http-server/dist/http-server.js:50:21)
    at WebSocketServer.start (/home/georman/Documents/loopback4-example-websocket-app/dist/websockets/websocket.server.js:61:31)
    at TodoListApplication.start (/home/georman/Documents/loopback4-example-websocket-app/dist/websockets/websocket.application.js:17:29)
    at main (/home/georman/Documents/loopback4-example-websocket-app/dist/index.js:14:15) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 3000
}

**Comment by Arbuzov** [comment]
Seems it`s a design. The loopback uses an external web socket server from socket.io. It demands it`s own port.
I solve it by using Nginx as a reverse proxy.

**Comment by alexkander** [comment]
hi guys, there are a new package for loopback socketio: [https://www.npmjs.com/package/@loopback/socketio](https://www.npmjs.com/package/@loopback/socketio).

I'll close this issue.

Regards.
